"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
type TeamTask={id:number;title:string;description:string|null;status:"Open"|"InProgress"|"Completed";createdBy:string;createdAt:string;dueDate:string|null;assignedTo:string|null;startedAt:string|null;completedBy:string|null;completedAt:string|null};
export default function TaskBoard({name}:{name:string}){
 const[active,setActive]=useState<TeamTask[]>([]),[completed,setCompleted]=useState<TeamTask[]>([]);const[tab,setTab]=useState<"active"|"completed">("active");const[title,setTitle]=useState(""),[description,setDescription]=useState(""),[dueDate,setDueDate]=useState("");const[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch("/api/tasks",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error??"Could not load tasks.");setActive(b.active);setCompleted(b.completed);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load tasks.")}},[]);
 useEffect(()=>{load();const timer=setInterval(load,3000);return()=>clearInterval(timer)},[load]);
 async function action(path:string,body:object={}){setBusy(true);setError("");try{const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error??"Something went wrong.");await load();return true}catch(e){setError(e instanceof Error?e.message:"Something went wrong.");return false}finally{setBusy(false)}}
 async function addTask(e:FormEvent){e.preventDefault();if(await action("/api/tasks",{title,description,dueDate})){setTitle("");setDescription("");setDueDate("")}}
 const visible=tab==="active"?active:completed;const formatDate=(value:string)=>new Date(`${value}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"});const openCount=active.filter(task=>task.status==="Open").length;const workingCount=active.filter(task=>task.status==="InProgress").length;const today=new Date().toISOString().slice(0,10);
 return <><header><div className="brand"><span>✓</span> TaskFlow</div><div className="user"><b>{name[0]?.toUpperCase()}</b><span>{name}</span><a href="/signout-with-chatgpt?return_to=%2F">Log out</a></div></header><main className="page">
 <section className="hero"><div className="hero-copy"><p className="kicker">GOOD TO SEE YOU, {name.split(" ")[0].toUpperCase()}</p><h1>Move work forward,<br/><em>together.</em></h1><p>A calm, shared place for your team to plan, claim, and complete the work that matters.</p></div><div className="stats"><div><b>{active.length}</b><span>Active</span></div><div><b>{workingCount}</b><span>In progress</span></div><div><b>{completed.length}</b><span>Completed</span></div></div></section>
 <section className="new-task"><div className="form-heading"><div><p className="kicker">QUICK ADD</p><h2>Create a task</h2></div><span>{openCount} ready to claim</span></div><form onSubmit={addTask}><label><span>Task name</span><input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder="What needs to be done?"/></label><label><span>Details</span><textarea maxLength={2000} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Add helpful context (optional)"/></label><label className="due-field"><span>Complete by</span><input type="date" required value={dueDate} min={today} onChange={e=>setDueDate(e.target.value)}/></label><button disabled={busy}>{busy?"Saving…":"Add task"}<span>→</span></button></form></section>
 {error&&<div className="error">{error}</div>}<nav className="tabs"><button className={tab==="active"?"selected":""} onClick={()=>setTab("active")}>Active <i>{active.length}</i></button><button className={tab==="completed"?"selected":""} onClick={()=>setTab("completed")}>Completed <i>{completed.length}</i></button></nav>
 <section className="list">{visible.length===0?<div className="empty"><span>✓</span><h3>{tab==="active"?"All clear":"No completed tasks yet"}</h3><p>{tab==="active"?"Add a task above to get your team moving.":"Finished work will appear here."}</p></div>:visible.map(task=><article className={`task ${task.status==="Completed"?"done":""}`} key={task.id}><div className="task-main"><span className={`status-dot ${task.status.toLowerCase()}`}></span><div className="task-content"><div className="task-title-row"><h3>{task.title}</h3><span className={`status-label ${task.status.toLowerCase()}`}>{task.status==="InProgress"?"In progress":task.status}</span></div>{task.description&&<p>{task.description}</p>}<small>Added by {task.createdBy} · {new Date(task.createdAt).toLocaleDateString()}</small><div className="task-meta">{task.dueDate&&<div className={`due-date ${task.status!=="Completed"&&task.dueDate<today?"overdue":""}`}>◷ {task.status!=="Completed"&&task.dueDate<today?"Overdue · ":"Due · "}{formatDate(task.dueDate)}</div>}{task.status==="InProgress"&&<div className="assigned">↻ {task.assignedTo} is working on this</div>}{task.status==="Completed"&&<div className="completed">✓ Completed {new Date(task.completedAt!).toLocaleDateString()} by {task.completedBy}</div>}</div></div></div>{task.status==="Open"&&<button className="start" disabled={busy} onClick={()=>action(`/api/tasks/${task.id}/start`)}>Start work</button>}{task.status==="InProgress"&&task.assignedTo===name&&<button className="finish" disabled={busy} onClick={()=>action(`/api/tasks/${task.id}/complete`)}>Mark finished</button>}{task.status==="InProgress"&&task.assignedTo!==name&&<button className="claimed" disabled>Claimed</button>}</article>)}</section></main></>}
